title: "Parth Pandya"
email: parthpandyappp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A portfolio site related to my MLH contributions. Doing this under Local Hack Day's event!
baseurl: "/" 
url: "https://parthpandyappp.github.io/MLH-Portfolio/" 
twitter_username: pandyaparthppp
github_username:  parthpandyappp

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
